system:
  name: "Multi-Agent Research Assistant"
  version: "1.0.0"
  log_level: "INFO"

models:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  vision_model: "microsoft/DiT-base-patch16-224"
  ocr_model: "easyocr"
  llm_model: "gpt-3.5-turbo"

databases:
  vector_store:
    type: "chroma"
    persist_directory: "./data/embeddings"
  knowledge_graph:
    type: "networkx"
    persist_directory: "./data/knowledge_graphs"

agents:
  research_agent:
    max_iterations: 5
    temperature: 0.3
  implementation_agent:
    max_iterations: 3
    temperature: 0.1
  experiment_agent:
    max_iterations: 4
    temperature: 0.5
  critique_agent:
    max_iterations: 3
    temperature: 0.2
